FILES = DelatorrkeKp2.java heap.java node.java

DelatorreKp1.class : $(FILES)
	@echo -n Compiling project...
	@javac DelatorreKp2.java
	@echo Done

run :
	@java DelatorreKp2

clean :
	@echo -n Cleaning...
	@rm -rf *.class
	@echo Done
