DelatorreKp1.class : DelatorreKp1.java tree.java node.java
	@echo -n Compiling project...
	@javac DelatorreKp1.java
	@echo Done

run :
	@java DelatorreKp1

clean :
	@echo -n Cleaning...
	@rm -rf *.class
	@echo Done
